name: Golang CI

on:
  push:
    branches: ["*"]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    name: CI Build
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18'
    - name: Setup tools
      run: |
        go install golang.org/x/lint/golint@latest
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test Project
      run: |
        make test
    - name: Build Project
      run: |
        make

